US898092: Create new lightweight image without plugins
CAFapi/opensuse-opensearch1-image pull request #34
Opened 2024-03-21 09:04 UTC by raghavendran-gopalakrishnan

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=898092

2024-03-21 09:05 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFapi&REPO_NAME=opensuse-opensearch1-image&BRANCH_NAME=US898092) to go ahead and create the build...

2024-03-21 09:12 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFapi/job/CAFapi~opensuse-opensearch1-image~US898092~CI

2024-03-21 09:56 UTC, michael-bryson commented
@raghavendran-gopalakrishnan In the build log I see:
```
2024-03-21T09:50:41.050497441Z [WARNING] Unknown file extension: /wd/src/main/docker/Dockerfile.noPlugins
2024-03-21T09:50:41.056797942Z [WARNING] Unable to find a comment style definition for some files. You may want to add a custom mapping for the relevant file extensions.
```
This means the new Dockerfile.noPlugins will not be automatically managed by the license plugin. Therefore you should add a custom mapping to the pom similar to how the java images are done, see: https://github.com/CAFapi/opensuse-java17-images/blob/main/pom.xml#L127

2024-03-21 10:10 UTC, raghavendran-gopalakrishnan commented
> @raghavendran-gopalakrishnan In the build log I see:
> 
> ```
> 2024-03-21T09:50:41.050497441Z [WARNING] Unknown file extension: /wd/src/main/docker/Dockerfile.noPlugins
> 2024-03-21T09:50:41.056797942Z [WARNING] Unable to find a comment style definition for some files. You may want to add a custom mapping for the relevant file extensions.
> ```
> 
> This means the new Dockerfile.noPlugins will not be automatically managed by the license plugin. Therefore you should add a custom mapping to the pom similar to how the java images are done, see: https://github.com/CAFapi/opensuse-java17-images/blob/main/pom.xml#L127

Sure thanks Michael.

2024-03-21 10:59 UTC, raghavendran-gopalakrishnan commented
Build took 1 hour 40 minutes. Should we do something about it ?

2024-03-21 11:01 UTC, michael-bryson commented
> Build took 1 hour 40 minutes (just the Upload phase took almost an hour). Should we do something about it ?

Its the upload step, I have noticed the trivvy scans taking a lot longer recently @dermot-hardy do you know whats going on there?

2024-03-21 11:04 UTC, andyreidz requested changes
Can you reduce the duplication between this new image and the existing one?

2024-03-21 11:08 UTC, michael-bryson commented
> Can you reduce the duplication between this new image and the existing one?

@raghavendran-gopalakrishnan Look at the tomcat images for an example, the opensuse-tomcat-jre17-image builds on top of the juli image: https://github.com/CAFapi/opensuse-tomcat-jre17-image/blob/main/opensuse-tomcat-jre17-image/src/main/docker/Dockerfile

You should be able to do something similar and remove the plugins from the already built image.

2024-03-21 11:16 UTC, andyreidz commented
> > Can you reduce the duplication between this new image and the existing one?
> 
> @raghavendran-gopalakrishnan Look at the tomcat images for an example, the opensuse-tomcat-jre17-image builds on top of the juli image: https://github.com/CAFapi/opensuse-tomcat-jre17-image/blob/main/opensuse-tomcat-jre17-image/src/main/docker/Dockerfile
> 
> You should be able to do something similar and remove the plugins from the already built image.

2024-03-21 11:17 UTC, andyreidz commented
Unfortunately we can't do it that way because of what Dermot discovered with the CVE scanner (It checks all layers)

2024-03-21 11:18 UTC, raghavendran-gopalakrishnan commented
@andyreidz so what do you propose instead ?

2024-03-21 11:19 UTC, michael-bryson commented
> Unfortunately we can't do it that way because of what Dermot discovered with the CVE scanner (It checks all layers)

If you do the removal in a builder image and then only copy the stuff across to an actual image will that not work? We would have to do that anyway as even with the current approach here the layers will show the CVEs.

2024-03-21 14:10 UTC, andyreidz requested changes

2024-03-21 14:10 UTC, andyreidz commented on src/main/docker/Dockerfile.noPlugins
> +COPY --from=os1-image /usr/share/opensearch/jdk /usr/share/opensearch/jdk
COPY --from=os1-image /usr/share/opensearch/jdk /usr/share/opensearch/jdk

This will copy the jdk into the history of the image

2024-03-21 15:13 UTC, michael-bryson requested changes

2024-03-21 17:36 UTC, michael-bryson commented on src/main/docker/Dockerfile
> +RUN OPENSEARCH_JAVA_OPTS="$(echo ${https_proxy} | sed -E 's/^.*:\/\/(.*):([0-9]*).*/-Dhttps.proxyHost=\1 -Dhttps.proxyPort=\2/')" \
Why are these changes necessary?

2024-03-21 17:38 UTC, raghavendran-gopalakrishnan commented on src/main/docker/Dockerfile
> +RUN OPENSEARCH_JAVA_OPTS="$(echo ${https_proxy} | sed -E 's/^.*:\/\/(.*):([0-9]*).*/-Dhttps.proxyHost=\1 -Dhttps.proxyPort=\2/')" \
Actually not. I have updated now.

2024-03-21 17:40 UTC, michael-bryson approved these changes
This looks good to me now, before you merge can you use this in a classification worker build to make sure there are no issues.

Also @dermot-hardy does this look like it will get past the CVE scanner?

2024-03-21 17:41 UTC, raghavendran-gopalakrishnan commented
> This looks good to me now, before you merge can you use this in a classification worker build to make sure there are no issues.
> 
> Also @dermot-hardy does this look like it will get past the CVE scanner?

Yes I will do that, thanks Michael.

2024-03-21 19:34 UTC, dermot-hardy approved these changes

2024-03-22 06:14 UTC, raghavendran-gopalakrishnan commented
Tested this dev build with classification worker, works well.

2024-03-22 06:16 UTC, merged